config/routes.rb
Rails.application.routes.draw do
  root 'item#index'
  get 'item/new' => 'item#new', as: 'item_new'
  post 'item/new' => 'item#create'
  get 'item/edit/:id' => 'item#edit', as: 'item_edit'
  put 'item/edit/:id' => 'item#update'
  delete 'item/delete/:id' => 'item#delete', as:'item_delete'
  get 'item/:id' => 'item#show', as: 'item_show'
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
  	@items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
  	@item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def delete
    @item = Item.find(params[:id])
    if @item.destroy
      redirect_to root_path
    else
      render item_show_path(@item)
    end
  end

  private
  def item_params
    params.require(:item).permit(:id, :name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/item/edit.html.erb
<%= form_for :item, :method => 'put' do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
	</p>
    <p>
        <%= f.label :price %><br>
        <%= f.number_field :price %>
	</p>
    <p>
        <%= f.submit %>
    </p> 
<% end %>

app/views/item/index.html.erb
<h1>Item listing</h1>
<% @items.each do |item| %>
  <p><%= link_to item.name, item_show_path(item) %></p>
<% end %>
<h2><%= link_to "Create new item >>", item_new_path %></h2>

app/views/item/new.html.erb
<%= form_for :item do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
    <p>
	    <%= f.label :price %><br>
	    <%= f.number_field :price %>
	</p>
    <p>
        <%= f.submit %>
	</p> 
<% end %>

app/views/item/show.html.erb
<h1><%= @item.name %></h1>
<p>&euro;<%= @item.price %></p>
<p><%= link_to "Edit Item", item_edit_path(@item) %></p>
 <p><%= link_to "Delete Item", item_delete_path(@item),
   method: :delete, data: { confirm: "Are you sure you want to delete
   this item?" } %></p>
<p><%= link_to "<< Back to full listing", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssignmentApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>